# Cloud Build configuration for deploying to Cloud Run
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/groeimetai-platform:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/groeimetai-platform:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://groeimetai-platform-$PROJECT_NUMBER.run.app'
      - '.'
    timeout: '1200s'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/groeimetai-platform'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'groeimetai-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/groeimetai-platform:$COMMIT_SHA'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'
      - '--set-secrets'
      - 'PINECONE_API_KEY=pinecone-api-key:latest'
      - '--set-secrets'
      - 'NEXTAUTH_SECRET=nextauth-secret:latest'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest'
      - '--timeout'
      - '300s'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/groeimetai-platform:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/groeimetai-platform:latest'

# Build timeout
timeout: '2000s'

# Machine type for builds
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY