steps:
  # Build the Docker image (no build args needed - using .env.production)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/groeimetai-platform:$COMMIT_SHA'
      - '.'
    
images:
  - 'gcr.io/$PROJECT_ID/groeimetai-platform:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  
# No substitutions needed - all public config is in .env.production