steps:
  # Build the Docker image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/groeimetai-platform:$COMMIT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_BLOCKCHAIN_ENABLED=true'
      - '--build-arg'
      - 'NEXT_PUBLIC_DEFAULT_NETWORK=polygon'
      - '--build-arg'
      - 'NEXT_PUBLIC_CERTIFICATE_CONTRACT_POLYGON=${_NEXT_PUBLIC_CERTIFICATE_CONTRACT_POLYGON}'
      - '--build-arg'
      - 'NEXT_PUBLIC_PINATA_GATEWAY=https://gateway.pinata.cloud'
      - '.'
    
images:
  - 'gcr.io/$PROJECT_ID/groeimetai-platform:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  
# Note: You need to set these substitutions in Cloud Build trigger settings
substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: 'must-be-set-in-trigger'
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'must-be-set-in-trigger'
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'must-be-set-in-trigger'
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'must-be-set-in-trigger'
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 'must-be-set-in-trigger'
  _NEXT_PUBLIC_FIREBASE_APP_ID: 'must-be-set-in-trigger'
  _NEXT_PUBLIC_CERTIFICATE_CONTRACT_POLYGON: 'must-be-set-in-trigger'