#!/bin/bash

# Script to help set up GitHub secrets for deployment
# This script shows which secrets need to be configured

echo "==================================="
echo "GitHub Secrets Setup Instructions"
echo "==================================="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo "Go to: https://github.com/groeimetai/groeimetai-platform/settings/secrets/actions"
echo ""
echo "Required Firebase Client-Side Secrets (from Firebase Console > Project Settings):"
echo "  - NEXT_PUBLIC_FIREBASE_API_KEY"
echo "  - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" 
echo "  - NEXT_PUBLIC_FIREBASE_PROJECT_ID"
echo "  - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
echo "  - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
echo "  - NEXT_PUBLIC_FIREBASE_APP_ID"
echo ""
echo "Required Firebase Admin Secrets:"
echo "  - FIREBASE_PROJECT_ID (same as NEXT_PUBLIC_FIREBASE_PROJECT_ID)"
echo "  - FIREBASE_CLIENT_EMAIL (from service account JSON)"
echo "  - FIREBASE_PRIVATE_KEY (from service account JSON - include the \\n characters)"
echo ""
echo "Other Required Secrets:"
echo "  - MOLLIE_API_KEY"
echo "  - OPENAI_API_KEY"
echo "  - PINECONE_API_KEY"
echo "  - PINECONE_ENVIRONMENT"
echo "  - BLOCKCHAIN_PRIVATE_KEY (optional)"
echo "  - PINATA_API_KEY (optional)"
echo "  - PINATA_SECRET_KEY (optional)"
echo "  - RESEND_API_KEY (optional)"
echo "  - REDIS_URL (optional)"
echo "  - N8N_API_KEY (optional)"
echo "  - N8N_WEBHOOK_URL (optional)"
echo ""
echo "To get Firebase configuration values:"
echo "1. Go to Firebase Console: https://console.firebase.google.com"
echo "2. Select your project (groeimetai-platform)"
echo "3. Click the gear icon > Project settings"
echo "4. Under 'Your apps' section, find your web app"
echo "5. Copy the firebaseConfig values"
echo ""
echo "Example values from your local .env file:"
if [ -f ".env.local" ]; then
    echo ""
    echo "Found .env.local file. Here are your Firebase values:"
    grep "^NEXT_PUBLIC_FIREBASE_" .env.local || echo "No Firebase values found in .env.local"
else
    echo ""
    echo "No .env.local file found. Create one with your Firebase config."
fi

echo ""
echo "==================================="
echo "Quick copy-paste for GitHub CLI:"
echo "==================================="
echo ""
echo "If you have GitHub CLI installed, you can set secrets like this:"
echo ""
echo "# Example (replace with your actual values):"
echo "gh secret set NEXT_PUBLIC_FIREBASE_API_KEY --body \"your-api-key\""
echo "gh secret set NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN --body \"your-auth-domain\""
echo "gh secret set NEXT_PUBLIC_FIREBASE_PROJECT_ID --body \"groeimetai-platform\""
echo "gh secret set NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET --body \"groeimetai-platform.appspot.com\""
echo "gh secret set NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID --body \"your-sender-id\""
echo "gh secret set NEXT_PUBLIC_FIREBASE_APP_ID --body \"your-app-id\""
echo ""
echo "Or use the GitHub web interface for easier setup."